<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.11.10 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php 13149 2009-12-07 13:09:09Z nijel $
 * Date: Tue, 08 Jun 2010 09:51:40 GMT
 */

/* Servers configuration */
$i = 0;

/* Server localhost:/tmp/mysql5.sock (config:dbo331629839) [1] */
$i++;
$cfg['Servers'][$i]['host'] = 'localhost:/tmp/mysql5.sock';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'dbo331629839';
$cfg['Servers'][$i]['password'] = 'selena12';
$cfg['Servers'][$i]['only_db'] = 'db331629839';

$cfg['Servers'][$i]['AllowDeny']['order'] = '';

$cfg['Servers'][$i]['AllowDeny']['rules'] = array();



/* End of servers configuration */

?>
